#!/bin/bash
# Creates a double-clickable "Harness Quote.app" on your Desktop, wired to
# this project's venv, so you can launch the app from Finder/Spotlight/
# Launchpad instead of the terminal. macOS only.
#
# Usage: ./scripts/make_desktop_launcher.sh

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_DIR="$HOME/Desktop/Harness Quote.app"
MACOS_DIR="$APP_DIR/Contents/MacOS"

if [ ! -x "$PROJECT_DIR/.venv/bin/python" ]; then
    echo "No venv found at $PROJECT_DIR/.venv — run the setup steps in README.md first." >&2
    exit 1
fi

mkdir -p "$MACOS_DIR"

cat > "$APP_DIR/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>Harness Quote</string>
    <key>CFBundleDisplayName</key>
    <string>Harness Quote</string>
    <key>CFBundleIdentifier</key>
    <string>com.local.harnessquote</string>
    <key>CFBundleVersion</key>
    <string>1.0</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleExecutable</key>
    <string>launch</string>
    <key>LSMinimumSystemVersion</key>
    <string>11.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
</dict>
</plist>
PLIST

cat > "$MACOS_DIR/launch" <<LAUNCH
#!/bin/bash
# Launches the Harness Quoting app. Generated by make_desktop_launcher.sh
# — re-run that script if you move the project folder.
LOG_FILE="$PROJECT_DIR/app_launch.log"
cd "$PROJECT_DIR" || exit 1
exec "$PROJECT_DIR/.venv/bin/python" main.py >"\$LOG_FILE" 2>&1
LAUNCH

chmod +x "$MACOS_DIR/launch"
xattr -c "$APP_DIR" 2>/dev/null || true

echo "Created \"$APP_DIR\" — double-click it (or Spotlight-search \"Harness Quote\") to launch the app."
